language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python on Xenial Linux"
      python: 3.7
              2.7
      before_install:

      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
script:
    pytest
