language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python on Xenial Linux"
      python:
        3.8
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    matrix:
      include:
        - name: "Python 2.7.14 on macOS 10.13"
        os: osx
        osx_image: xcode9.3  # Python 2.7.14_2 running on macOS 10.13
        language: shell  # 'language: python' errors on Travis CI macOS
install:
script:
    pytest
